#!/bin/bash

set -e

LOCAL=false
while [[ $# > 0 ]]; do
    key="$1"
    echo $key
    case $key in
        -l|--local)
            LOCAL="true"
            shift
        ;;
        *)
        ;;
    esac
done

cd $(dirname $0)/..

TARGET="dist/artifacts/kubernetes-agent.tar.xz"

if [ "$LOCAL" != true ]; then
    rm -rf dist/artifacts
    mkdir -p dist/artifacts

    ARTIFACT_URL=$(curl -s https://api.github.com/repos/rancher/kubernetes-agent/releases/latest | jq -r .assets[0].browser_download_url)
    TAG=${TAG:-$(curl -s https://api.github.com/repos/rancher/kubernetes-agent/releases/latest | jq -r .tag_name)}
    echo "Downloading ${ARTIFACT_URL}"
    curl -o ${TARGET} -L ${ARTIFACT_URL}
fi

echo "Uncompressing..."
tar -xJvf ${TARGET} -C dist/artifacts/

TAG=${TAG:=dev}
IMAGE_NAME=${IMAGE:-"rancher/kubernetes-agent"}:${TAG}

echo "Building Docker image $IMAGE_NAME"
docker build --rm -t ${IMAGE_NAME} -f Dockerfile.dist .
